[build]
include = [
    "showcase_3d_printer_anomaly_detection",
    ".python-version",
    "requirements.txt"
]

[[build.env]]
name="GOOGLE_ENTRYPOINT"
value="python3 -u showcase_3d_printer_anomaly_detection/runner.py"
